# pip install mkdocs==0.16.3
# pip install mkdocs-bootswatch

site_author: Simone Bifani
site_name: Simone Bifani
site_description: Home Page

#repo_name: GitLab
#repo_url: https://gitlab.cern.ch/bifani

pages:
- Home: index.md
- About: about.md
- Work: work.md
#- Publications: publications.md

theme: cosmo

extra:
  navigation: false
  search: false

extra_css: [_css/extra.css]
