name: Publish GitHub Pages

on:
  push:
    branches:
      - master

jobs:

  hugo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          persist-credentials: false
      - name: Build
        run: |
          sudo snap install hugo
          cd hugo
          hugo --cleanDestinationDir
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            BRANCH: gh-pages
            FOLDER: hugo/public
            CLEAN: true

  mkdocs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          persist-credentials: false
      - name: Build
        run: |
          pip install mkdocs==0.16.3
          pip install mkdocs-bootswatch
          cd mkdocs
          mkdocs build --clean
#      - name: Deploy
#        uses: JamesIves/github-pages-deploy-action@3.7.1
#        with:
#            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#            BRANCH: gh-pages
#            FOLDER: mkdocs/site
#            CLEAN: true
