name: Publish GitHub Pages

on:
  push:
    branches:
      - master

jobs:

  hugo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          persist-credentials: false

      - name: Build
        run: |
          sudo snap install hugo
          hugo

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            BRANCH: gh-pages
            FOLDER: public
            CLEAN: true
